title: Saurio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Luis Mella # add your name
author-img: david-freeman.jpg # add your photo
about-author: Blog personal, bitacora, ideas, referencias y analisis. # add description
twitter: seba_saurio
facebook: luissebastian.mella
github: # add your Github handle
linkedin: # add your Linkedin handle
email: luisebastian8@gmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
